CREATE TABLE ramen_reviews (
    review_id INT PRIMARY KEY,
    brand VARCHAR(255),
    variety VARCHAR(255),
    style VARCHAR(50),
    country VARCHAR(50),
    stars DECIMAL(3, 2)
);

INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (5307, 'Indomie', 'Mi Instan Rasa Rawon Pedas Mercon', 'Pack', 'Indonesia', 2.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (5245, 'Samyang Foods', 'Green Mala Buldak HOT Chicken Flavor Ramen', 'Pack', 'Indonesia', 3.75);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (5146, 'Mi Sedaap', 'Mi Goreng Spicy’licious', 'Pack', 'Indonesia', 4.25);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (5054, 'ABC', 'Selera Pedas Mi Goreng Cup Pedas Nampol', 'Cup', 'Indonesia', 3.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4978, 'Migelas', 'Rasa Sop Buntut ', 'Pack', 'Indonesia', 2.75);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4947, 'Mi Sedaap', 'Style Of Singapore Spicy Laksa', 'Pack', 'Indonesia', 3.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4921, 'Migelas', 'Protevit Rasa Kari Ayam', 'Pack', 'Indonesia', 3.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4913, 'Indomie', 'Mi Instan Rasa Cakalang', 'Pack', 'Indonesia', 4.25);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4910, 'Ginding', 'Cuanki Express', 'Cup', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4900, 'Migelas', 'Protevit Rasa Ayam Bawang', 'Pack', 'Indonesia', 4.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4891, 'Mi ABC', 'Rasa Ayam Bawang', 'Cup', 'Indonesia', 3.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4882, 'Mi Sedaap', 'Instant Mi Goreng Ayam Bakar Limau', 'Pack', 'Indonesia', 4.75);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4880, 'Indomie', 'Rasa Empal Gentong', 'Pack', 'Indonesia', 4.25);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4874, 'ABC', 'Selera Pedas Hot Chicken Lime Flavour', 'Cup', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4868, 'Migelas', 'Protevit Rasa Baso Sapi', 'Pack', 'Indonesia', 1.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4858, 'Mie Sedaap', 'Instant Mie Goreng Salero Padang', 'Pack', 'Indonesia', 4.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4853, 'Mie Sedaap', 'Soto Madura', 'Pack', 'Indonesia', 4.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4846, 'Indomie', 'Mi Instan Rasa Mi Kocok Bandung', 'Pack', 'Indonesia', 2.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4844, 'Meet Mee', 'Meet Mee Chili Pan Mee (Dry) (Fish Cake)', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4840, 'Indomie', 'Mi Instan Rasa Soto Banjar Limau Kuit', 'Pack', 'Indonesia', 4.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4837, 'Mie Sedaap', 'Kari Spsial Bumbu Kari Kental', 'Pack', 'Indonesia', 3.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4834, 'Indomie', 'Mi Instan Rasa Soto Medan', 'Pack', 'Indonesia', 3.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4830, 'ABC', 'Selera Pedas Hot Gulai Chicken Flavour', 'Cup', 'Indonesia', NULL);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4822, 'Ginding', 'Batagor Kuah Express', 'Cup', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4815, 'Migelas', 'Protevit Rasa Soto Ayam', 'Pack', 'Indonesia', 3.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4810, 'Mie Sedaap', 'Mi Kuah Instan Rasa White Curry', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4771, 'Indomie', 'Mi Instan Rasa Coto Makassar', 'Pack', 'Indonesia', 3.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4767, 'Indomie', 'Hype Abis Mi Goreng Kebab Rendang', 'Pack', 'Indonesia', 3.25);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4763, 'Indomie', 'Mi Goreng Rasa Sambal Rica-Rica', 'Pack', 'Indonesia', 3.75);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4759, 'Indomie', 'Rasa Soto Lamongan', 'Pack', 'Indonesia', 4.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4757, 'Mie Sedaap', 'Instant Cup Mi Goreng', 'Cup', 'Indonesia', 3.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4755, 'Indomie', 'Mi Goreng Rasa Cakalang', 'Pack', 'Indonesia', 4.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4752, 'Indomie', 'Rasa Soto Spesial', 'Pack', 'Indonesia', 4.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4723, 'Indomie', 'Mi Goreng Aceh', 'Pack', 'Indonesia', 4.25);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4719, 'Indomie', 'Mi Goreng Rasa Rendang', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4701, 'Kobe', 'Mi BonCabe Rasa Ramen Pedas', 'Pack', 'Indonesia', 3.75);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4681, 'Nissin', 'Geki Instant Fried Noodles HOT Carbo Flavour', 'Pack', 'Indonesia', 3.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4649, 'Indomie', 'Mi Instan Mi Keriting Goreng Spesial', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4643, 'Best Wok', 'Corn Bihun Hot & Spicy Fried Bihun', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4631, 'Kobe', 'Jiwa Pagi Mi Instan Ayam Bawang', 'Pack', 'Indonesia', 2.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4627, 'Best Wok', 'Corn Bihun Original Fried Bihun', 'Pack', 'Indonesia', 4.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4607, 'Indomie', 'Mi Goreng Rasa Ayam Pop', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4601, 'Indomie', 'Hype Abis Mi Kuah Rasa Seblak Hot Jeletot', 'Pack', 'Indonesia', 2.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4599, 'Kobe', 'Jiwa Pagi Mi Instan Mie Goreng', 'Pack', 'Indonesia', 3.25);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4597, 'Super Bubur', 'Rasa Ayam', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4595, 'Burung Layang Terbang', 'Mie Goreng Rasa Sambal Terasi', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4592, 'Koba', 'Jiwa Pagi Mi Instan Rasa Soto Segeer', 'Pack', 'Indonesia', 3.75);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4588, 'Indomie', 'Mi Instan Rasa Kaldu Ayam', 'Pack', 'Indonesia', 3.75);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4583, 'Indomie', 'Mi Goreng Rasa Cabe Ijo', 'Pack', 'Indonesia', 4.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4581, 'Indomie', 'Hype Abis Mi Goreng Rasa Ayam Geprek', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4578, 'BonCabe', 'Mi BonCabe Rasa Mie Goreng Level 15 Spicy', 'Pack', 'Indonesia', 4.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4513, 'Urai', 'Bihun Jagung Corn Vermicelli', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4503, 'Urai', 'Original x Ciptarasa Mi Goreng', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4489, 'Dara Urai', 'Flat x Cipratasa Rasa Ayam Bawang', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4431, 'Indomie', 'Mi Keriting Rasa Ayam Panggang', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4398, 'Burung Dara', 'Doroku Bihun Jagung', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4393, 'Indomie', 'Mi Gorenbg Original 50th Anniversary', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4106, 'Best Wok', 'Mi Goreng Black Pepper Seafood Flavor', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4105, 'Dara/Ciptarasa', 'Mi Goreng', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4104, 'Best Wok', 'Mi Goreng Original', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4103, 'Dara/Ciptarasa', 'Ayam Bawang', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4102, 'Best Wok', 'Mi Goreng Hot & Spicy', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4050, 'Mi Sedaap', 'Korean Spicy Chicken Mi Goreng', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (4009, 'Mi Sedaap', 'Selection Korean Spicy Soup', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (3989, 'Indomie', 'Instant Noodles Vegetable Flavored', 'Pack', 'Indonesia', 3.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (3907, 'Indomie', 'Instant Cup Noodles Mi Goreng Barbeque Chicken Flavour', 'Cup', 'Indonesia', 2.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (3906, 'Super Bihun', 'Instan Goreng Instant Fried Rice Noodles', 'Pack', 'Indonesia', 3.75);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (3885, 'Mi Sedaap', 'Selection Korean Spicy Chicken', 'Cup', 'Indonesia', 3.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (3844, 'Indomie', 'Instant Noodles Special Chicken Flavour', 'Pack', 'Indonesia', 4.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (3758, 'Mi Sedaap', 'Mi Segera Perisa Kari', 'Pack', 'Indonesia', 4.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (3705, 'Indomie', 'Mi Goreng Barbecue Chicken', 'Pack', 'Indonesia', 2.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (3679, 'Gurimi', 'Mi Instant Rasa Vegetarian', 'Pack', 'Indonesia', 3.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (3632, 'Gurimi', 'Rasa Kaldu Ayam', 'Pack', 'Indonesia', 3.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (3603, 'ABC President', 'Selera Pedas Spicy Stir Fry Cheese Noodles', 'Pack', 'Indonesia', 4.75);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (3602, 'ABC President', 'Mi Goreng Mi Instan Cup Stir Fry', 'Cup', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (3601, 'ABC President', 'Selera Pedas Spicy Stir Fry Beef Noodles', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (3556, 'ABC President', 'mi ABC Mi Instant Shrimp', 'Pack', 'Indonesia', 3.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (3486, 'Gurimi', 'Mi Goreng', 'Pack', 'Indonesia', 4.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (3462, 'ABC', 'Mi Instant Goreng', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (3423, 'ABC', 'Mi Instant Vegetable Flavor', 'Pack', 'Indonesia', 3.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (3270, 'FitMee', 'Konjac Chicken Soto', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (3268, 'FitMee', 'Konjac Fried Korean Noodle', 'Pack', 'Indonesia', 3.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (3083, 'Burung Layang Terbang', 'Kweitiau Kuah Rasa Ayam', 'Pack', 'Indonesia', 3.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (3051, 'Best Wok', 'Mi Goreng Sambal Seafood', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (3050, 'Chitato', 'Indomie Mi Goreng Potato Chips', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (3008, 'Indomie', 'Real Meat Mi Instan Goreng Rendang', 'Box', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (2971, 'Best Wok', 'Mi Goreng Hot & Spicy Instant Noodles', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (2923, 'Lemonilo', 'Mie Instan Alami Rasa Mie Goreng', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (2908, 'Best Wok', 'Mi Goreng Original Instant Noodles', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (2798, 'Indomie', 'Instant Noodles Mi Goreng Fried Noodles (Taiwan Only Version)', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (2771, 'Nissin', 'UFO Fried Ramen Japanese Sauce Flavour', 'Tray', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (2665, 'Alhami', 'Instant Noodle Instant Noodle Chicken Flavour', 'Pack', 'Indonesia', 3.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (2664, 'Maitri', 'Instant Noodle Vegetarian Soup', 'Pack', 'Indonesia', 3.25);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (2663, 'Alhami', 'Instant Noodle Soto Flavour', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (2662, 'Alhami', 'Instant Noodle Chicken Curry Flavour', 'Pack', 'Indonesia', 3.75);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (2661, 'Maitri', 'Vegetarian Mie Goreng', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (2660, 'Alhami', 'Instant Noodle Chicken Curry Flavour', 'Pack', 'Indonesia', 3.75);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (2659, 'Alhami', 'Instant Noodle Beef Flavour', 'Pack', 'Indonesia', 3.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (2658, 'Mikka', 'Noodle Snack Barbecue Flavor', 'Pack', 'Indonesia', 3.25);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (2657, 'Maitri', 'Extra Hot Vegetarian Mie Goreng', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (2656, 'Mikka', 'Noodle Snack Roast Corn Flavor', 'Pack', 'Indonesia', 4.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (2655, 'Alhami', 'Prawn Instant Noodles', 'Pack', 'Indonesia', 2.75);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (2654, 'Maitri', 'Vegetarian Hot Curry', 'Pack', 'Indonesia', 4.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (2653, 'Mikka', 'Noodle Snack Sambal Balado Chilli Sauce Flavor', 'Pack', 'Indonesia', 4.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (2652, 'Maitri', 'Vegetarian Rasa Soto', 'Pack', 'Indonesia', 4.25);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (2651, 'Alhami', 'Mi Goreng Spesial', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (2549, 'Nissin', 'Gekikara Ramen Extra Hot Ramen Goreng', 'Pack', 'Indonesia', 4.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (2507, 'Indomie', 'RMy Noodlez Rumput Laut', 'Pack', 'Indonesia', 4.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (2463, 'Nissin', 'Gekikara Ramen Rasa Pedas', 'Pack', 'Indonesia', 3.25);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (2438, 'World O'' Noodle', 'Mi Goreng Original Flavour Fried Noodles', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (2417, 'Super Bihun', 'Bihun Kuah Rasa Baso Sapi', 'Pack', 'Indonesia', 3.75);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (2399, 'Indomie', 'My Noodles Mi Goreng Pizza Cheese', 'Pack', 'Indonesia', 4.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (2374, 'World O'' Noodle', 'Mi Goreng Garlic Flavour Fried Noodles', 'Pack', 'Indonesia', 4.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (2075, 'Mi Sedaap', 'Mi Segera Mi Goreng Ayam Krispi', 'Pack', 'Indonesia', 4.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (2052, 'Indomie', 'Pop Mie Mi Instan Cup Rasa Ayam', 'Cup', 'Indonesia', 3.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1922, 'Mie Sedaap', 'Instant Cup Mi Kuah Rasa Baso Spesial', 'Cup', 'Indonesia', 1.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1856, 'Indomie', 'Instant Cup Noodles Mi Goreng Fried Noodles', 'Cup', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1822, 'Mi Sedaap', 'Mi Kuah Rasa Baso Spesial', 'Pack', 'Indonesia', 3.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1750, 'Mi Sedaap', 'Instant Cup Mi Kuah Rasa Soto', 'Cup', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1737, 'Mi Sedaap', 'Instant Cup Mi Goreng', 'Cup', 'Indonesia', 3.75);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1721, 'Salam Mie', 'Mi Goreng Dengan Abon', 'Pack', 'Indonesia', 4.25);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1670, 'Tropicana Slim', 'Less Fat Noodles Grilled Chicken', 'Pack', 'Indonesia', 3.75);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1603, 'Salam Mie', 'Mi Goreng Ala Jawa Dengan Sambal Cabe Asli', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1494, 'Indomie', 'Pop Mie Chicken Flavour Cup Noodles', 'Cup', 'Indonesia', 3.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1406, 'La Fonte', 'Spaghetti With Mushroom Sauce', 'Pack', 'Indonesia', 3.75);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1402, 'Pop Bihun', 'Spesial Rasa Kari Ayam Pedas', 'Pack', 'Indonesia', 3.75);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1390, 'Indomie', 'Mi Goreng Rasa Iga Penyet', 'Pack', 'Indonesia', 4.75);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1340, 'Indomie', 'Taste Of Asia Mi Goreng Rasa Bulgogi Ala Korea', 'Pack', 'Indonesia', 2.75);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1331, 'Indomie', 'Taste Of Asia Mi Kuah Rasa Tom Yum Ala Thailand', 'Pack', 'Indonesia', 3.75);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1313, 'Healtimie', 'Green Barley Noodle Vegetable Soup', 'Pack', 'Indonesia', 3.25);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1311, 'Pop Bihun', 'Spesial Rasa Soto Ayam', 'Pack', 'Indonesia', 4.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1297, 'GaGa', 'Mie Gepeng Kuah Rasa Ayam Lada Hitam', 'Pack', 'Indonesia', 3.25);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1267, 'ABC', 'Mi Cup Rasa Soto Ayam Chicken Soto Flavour', 'Cup', 'Indonesia', 3.75);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1266, 'ABC', 'Selera Pedas Mi Goreng Cup Rasa Gulai Ayam Pedas Hot Gulai Chicken', 'Cup', 'Indonesia', 4.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1265, 'ABC', 'Rasa Ayam Bawang Chicken Onion Flavour', 'Cup', 'Indonesia', 3.75);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1264, 'ABC', 'Selera Pedas Mi Goreng Cup Rasa Ayam Pedas Limau Hot Chicken Lemon Flavour', 'Cup', 'Indonesia', 4.25);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1262, 'ABC', 'Mi Cup Rasa Kari Ayam Chicken Curry Flavour', 'Cup', 'Indonesia', 3.75);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1261, 'Eat & Go', 'Rasa Baso Sapi Meat Ball Mi Instan Cup', 'Cup', 'Indonesia', 3.75);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1260, 'ABC', 'Mi Goreng Pangsit Fried Noodle With Dumpling', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1259, 'Eat & Go', 'Chicken Onion Mi Instan Cup', 'Cup', 'Indonesia', 3.75);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1258, 'President', 'Mi Goreng Rasa Ayam Chicken Flavoured Fried Noodle', 'Pack', 'Indonesia', 4.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1257, 'ABC', 'Mi Goreng Spesial Special Fried Noodle', 'Cup', 'Indonesia', 4.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1256, 'Eat & Go', 'Curry Chicken Mi Instan Cup', 'Cup', 'Indonesia', 4.25);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1239, 'SuperMi', 'Rasa Ayam Spesial', 'Pack', 'Indonesia', 4.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1232, 'GaGa', 'Mie Gepeng Kuah Rasa Ayam Bawang Pedas', 'Pack', 'Indonesia', 3.25);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1221, 'ABC', 'Selera Pedas Hot Semur Chicken Flavour', 'Pack', 'Indonesia', 4.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1215, 'GaGa', 'Mi Instan Cup Milk Chicken Soup', 'Cup', 'Indonesia', 4.75);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1214, 'Eat & Go', 'Rendang Beef Flavour Fried Instant Noodle', 'Cup', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1203, 'GaGa', 'Mie Gepeng Kuah Rasa Soto Cabe Hijau', 'Pack', 'Indonesia', 3.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1191, 'GaGa', 'Seribu 1000 Goreng Spesial', 'Pack', 'Indonesia', 4.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1177, 'ABC', 'Mi ABC Rasa Ayam Bawang (Onion Chicken)', 'Pack', 'Indonesia', 4.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1175, 'Healtimie', 'Green Barley Noodle Milk Chicken Soup', 'Pack', 'Indonesia', 4.25);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1173, 'Pop Bihun', 'Spesial Goreng Special', 'Pack', 'Indonesia', 3.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1161, 'GaGa', '100 Green Chilli Soto Flavour', 'Pack', 'Indonesia', 3.75);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1135, 'Indomie', 'Instant Noodle Beef & Lime Flavour', 'Pack', 'Indonesia', 4.25);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1126, 'GaGa', 'Mie Jepeng Goreng Rasa Ayam Lada Hitam', 'Pack', 'Indonesia', 4.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1120, 'ABC', 'Selera Pedas Mi Rebus Hot Gulai Flavor', 'Pack', 'Indonesia', 4.75);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1114, 'Maitri', 'Vegetarian Fried Noodles (Mie Goreng)', 'Pack', 'Indonesia', 4.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1109, 'La Fonte', 'Spaghetti With Bolognese Sauce', 'Box', 'Indonesia', 4.25);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1101, 'Eat & Go', 'Spicy Chicken Mi Instan Cup', 'Cup', 'Indonesia', 4.25);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1098, 'Tropicana Slim', 'Low Fat Noodles Hainan Chicken', 'Pack', 'Indonesia', 3.75);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (1082, 'Indomie', 'Mi Goreng Cabe Ijo', 'Pack', 'Indonesia', 4.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (909, 'Indomie', 'Kriuuk Bawang', 'Pack', 'Indonesia', 4.25);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (901, 'Sarimi', 'Rasa Ayam Bawang', 'Pack', 'Indonesia', 3.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (895, 'SuperMi', 'Sedaaap Mi Goreng', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (892, 'ABC', 'Selera Pedas Hot Tomato Soup Flavor', 'Pack', 'Indonesia', 4.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (882, 'SuperMi', 'GoBang', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (876, 'Sarimi', 'Soto Koya Pedasss', 'Pack', 'Indonesia', 3.25);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (870, 'SuperMi', 'Mi Keriting Rasa Ayam Bawang', 'Pack', 'Indonesia', 3.75);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (867, 'Indomie', 'Rasa Coto Makassar', 'Pack', 'Indonesia', 4.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (863, 'Indomie', 'Special Fried Curly Noodle (Local)', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (858, 'Indomie', 'Rasa Mi Cakalang', 'Pack', 'Indonesia', 4.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (852, 'SuperMi', 'Sedaaap Mi Kuah Rasa Kari Ayam', 'Pack', 'Indonesia', 4.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (838, 'Sarimi', 'Soto Koya Gurih', 'Pack', 'Indonesia', 4.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (834, 'Indomie', 'Mi Goreng Kriuuk Pedas', 'Pack', 'Indonesia', 3.75);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (818, 'SuperMi', 'Sedaaap Mi Kuah Rasa Soto', 'Pack', 'Indonesia', 4.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (814, 'Indomie', 'Beef', 'Pack', 'Indonesia', 3.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (810, 'ABC', 'Selera Pedas Mi Goreng Hot Chicken Lemon', 'Pack', 'Indonesia', 4.25);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (807, 'SuperMi', 'Super Rasa Ayam Bawang', 'Pack', 'Indonesia', 4.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (802, 'Sarimi', 'Isi 2 Mi Goreng Rasa Ayam Kecap', 'Pack', 'Indonesia', 4.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (794, 'Sarimi', 'Soto Koya Jeruk Nipis', 'Pack', 'Indonesia', 4.75);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (789, 'SuperMi', 'GoKar', 'Pack', 'Indonesia', 4.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (785, 'Sarimi', 'Isi 2 Rasa Soto', 'Pack', 'Indonesia', 3.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (779, 'Indomie', 'Mi Goreng Kriuuk Ayam', 'Pack', 'Indonesia', 3.75);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (776, 'Sarimi', 'Isi 2 Rasa Kari spesial', 'Pack', 'Indonesia', 3.75);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (774, 'Indomie', 'Rasa Sup Sayuran Vegan', 'Pack', 'Indonesia', 2.25);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (771, 'Mi Sedaap', 'Mi Kuah Rasa Ayam Bawang', 'Pack', 'Indonesia', 4.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (765, 'Super Bihun', 'Kuah Rice Noodles', 'Pack', 'Indonesia', 4.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (757, 'Indomie', 'Mi Goreng Vegan', 'Pack', 'Indonesia', 4.25);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (740, 'Indomie', 'Mi Goreng Sate (Local)', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (734, 'Indomie', 'Mi Goreng Rasa Ayam Panggang Jumbo (Local)', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (733, 'Indomie', 'Rasa Soto Betawi', 'Pack', 'Indonesia', 4.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (732, 'Indomie', 'Curly Noodle With Chicken Chilli Paddi', 'Pack', 'Indonesia', 4.25);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (731, 'Indomie', 'Rasa Mi Kocok Bandung', 'Pack', 'Indonesia', 3.25);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (730, 'Indomie', 'Rasa Soto Banjar Limau Kulit', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (729, 'Indomie', 'Mi Goreng Jumbo Beef', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (728, 'Indomie', 'Rasa Kari Ayam Medan', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (727, 'Indomie', 'Rasa Empal Gentong', 'Pack', 'Indonesia', 4.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (726, 'Indomie', 'Mi Goreng Cakalang', 'Pack', 'Indonesia', 4.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (725, 'Indomie', 'Mi Goreng Instant Cup Noodles', 'Cup', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (724, 'Indomie', 'Curly Noodle With Laksa Chilli', 'Pack', 'Indonesia', 3.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (723, 'Indomie', 'Mi Goreng Barbecue Chicken', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (715, 'Indomie', 'Mi Goreng Rendang (Import)', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (686, 'Mi Sedaap', 'Mi Segera Mi Goreng Perisa Sambal Goreng', 'Pack', 'Indonesia', 4.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (685, 'Indomie', 'Rasa Sup Buntut Oxtail Soup', 'Pack', 'Indonesia', 2.75);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (682, 'Indomie', 'Instant Cup Noodles Mi Goreng Satay', 'Cup', 'Indonesia', 4.25);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (676, 'Indomie', 'Spicy Coconut Shrimp', 'Pack', 'Indonesia', 4.75);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (655, 'Cap Atoom Bulan', 'Mie Telor Asli', 'Pack', 'Indonesia', 3.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (651, 'Mi Sedaap', 'Mi Segera Mi Sup Perisa Kari Ayam', 'Pack', 'Indonesia', 4.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (556, 'Mi Sedaap', 'Mi Goreng Perisa Asli', 'Pack', 'Indonesia', 4.75);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (552, 'Super Bihun', 'Kuah Rasa Baso Sapi Rice Noodles', 'Pack', 'Indonesia', 3.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (549, 'Mi Sedaap', 'Supreme Soto', 'Pack', 'Indonesia', 4.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (542, 'Mi Sedaap', 'Mi SupArtificial Chicken Special', 'Pack', 'Indonesia', 3.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (435, 'Mi Sedaap', 'Mie Sambal Goreng', 'Pack', 'Indonesia', 4.25);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (434, 'Mi Sedaap', 'Kari Spesial', 'Pack', 'Indonesia', 4.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (343, 'Super Bihun', 'Goreng Rice Noodles', 'Pack', 'Indonesia', 4.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (232, 'Indomie', 'Mi Goreng Jumbo Beef', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (231, 'Indomie', 'Onion Chicken', 'Pack', 'Indonesia', 4.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (105, 'Indomie', 'Special Fried Curly Noodle', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (102, 'Indomie', 'Soto Mie', 'Pack', 'Indonesia', 1.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (76, 'Indomie', 'Meatball Flavor', 'Pack', 'Indonesia', 2.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (75, 'Indomie', 'Mi Goreng Rendang', 'Pack', 'Indonesia', 4.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (53, 'Indomie', 'Chicken', 'Cup', 'Indonesia', 2.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (52, 'Indomie', 'Chicken Curry', 'Pack', 'Indonesia', 4.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (51, 'Indomie', 'Curly Noodles With Grilled Chicken', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (50, 'Indomie', 'Mi Goreng', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (49, 'Indomie', 'Mi Goreng Pedas Hot', 'Pack', 'Indonesia', 4.5);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (48, 'Indomie', 'Shrimp Flavor', 'Pack', 'Indonesia', 3.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (47, 'Indomie', 'Mi Goreng Jumbo Barbecue Chicken', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (46, 'Indomie', 'Mi Goreng Jumbo Meatball', 'Pack', 'Indonesia', 3.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (45, 'Indomie', 'Mi Goreng Sate', 'Pack', 'Indonesia', 5.0);
INSERT INTO ramen_reviews (review_id, brand, variety, style, country, stars) VALUES (44, 'Indomie', 'Special Chicken', 'Pack', 'Indonesia', 4.25);